### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np. 
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
import numpy as np

Поскольку в условиях задачи даны 2-мя списками числа из столбцов, то чтобы удобно перенести эти данные копипастом, 
а затем получить нужную матрицу, я создам сперва матрицу m, а затем транспонирую её в нужную матрицу a. Удобней, чем вручную переписывать числа из строк в условиях в столбцы.

In [3]:
m = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
a = m.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(0)
mean_a

array([2. , 8.4])

### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [6]:
N = 100

a_centered_t = a_centered.T # транспонирую a_centered чтобы удобно в 1 действие сделать скалярное произведение 
# первой строки-вектора (которая была столбцом в a_centered) на второй вектор. Подскажите, проверяющий; есть ли более удобный
# однострочный способ, функция, чтобы это сделать? Может я чего-то недоглядел?

a_centered_sp = a_centered_t[0] @ a_centered_t[1]
print(a_centered_sp)

res = a_centered_sp / (N - 1)
print(res)

8.0
0.08080808080808081


### Задание 4**

..проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [7]:
print(m) # транспонированный массив “a” я сделал ещё в первом задании
res2 = np.cov(m)
print(res2)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]
[[1.  2. ]
 [2.  4.3]]


Не понял. "a_centered_sp" не совпадает с элементом 2 массива "res2", хотя вроде и там и тут верно по заданию находил значение ковариации. Что не так?